title: ncraig.dev
author:
  name: Noah Craig
  email: noahcraig123@gmail.com
  github: Tyraeis
description: >-

baseurl: ""
url: "https://ncraig.dev"

collections:
  projects:
    output: true

featured_collections:
  - title: "Projects"
    collection: projects
  - title: "Posts"
    collection: posts

show_excerpts: true

# Build settings
plugins:
 - jekyll-feed