version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres
    shm_size: 256MB
  mygpo:
    build:
      context: .
      dockerfile: mygpo.Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres
    ports:
      - 8080:8080
networks:
  postgres:
